In [42]:
import pandas as pd
import numpy as np

# Importing dataset

In [100]:
dataset = pd.read_csv('pay1.csv')
# payment=1
#transfer=2
#cashout=3

In [47]:
dataset

step  type    amount  oldbalanceOrg  newbalanceOrg  oldbalanceDest  \
0     1     1   9839.64         170136      160296.36               0   
1     1     1   1864.28          21249       19348.72               0   
2     1     2    181.00            181           0.00               0   
3     1     3    181.00            181           0.00           21182   
4     1     1  11668.14         415554       29885.86               0   

   newbalanceDest  is fraud  
0               0         0  
1               0         0  
2               0         1  
3               0         1  
4               0         0

In [49]:
x=dataset.iloc[:, :-1].values
x

array([[1.0000000e+00, 1.0000000e+00, 9.8396400e+03, 1.7013600e+05,
        1.6029636e+05, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 1.8642800e+03, 2.1249000e+04,
        1.9348720e+04, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 2.0000000e+00, 1.8100000e+02, 1.8100000e+02,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 3.0000000e+00, 1.8100000e+02, 1.8100000e+02,
        0.0000000e+00, 2.1182000e+04, 0.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 1.1668140e+04, 4.1555400e+05,
        2.9885860e+04, 0.0000000e+00, 0.0000000e+00]])

In [51]:
y=dataset.iloc[:, -1].values
y

array([0, 0, 1, 1, 0], dtype=int64)

# split dataset

In [54]:
from sklearn.model_selection import train_test_split

In [56]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4,random_state=0)

In [58]:
len(x_train)
x_train

array([[1.000000e+00, 1.000000e+00, 1.864280e+03, 2.124900e+04,
        1.934872e+04, 0.000000e+00, 0.000000e+00],
       [1.000000e+00, 3.000000e+00, 1.810000e+02, 1.810000e+02,
        0.000000e+00, 2.118200e+04, 0.000000e+00],
       [1.000000e+00, 1.000000e+00, 1.166814e+04, 4.155540e+05,
        2.988586e+04, 0.000000e+00, 0.000000e+00]])

In [60]:
len(x_test)
x_test

array([[1.0000000e+00, 2.0000000e+00, 1.8100000e+02, 1.8100000e+02,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.0000000e+00, 9.8396400e+03, 1.7013600e+05,
        1.6029636e+05, 0.0000000e+00, 0.0000000e+00]])

In [62]:
len(y_train)
y_train

array([0, 1, 0], dtype=int64)

In [64]:
len(y_test)
y_test

array([1, 0], dtype=int64)

# feature scaling

In [67]:
from sklearn.preprocessing import StandardScaler

In [69]:
sc = StandardScaler()


In [71]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [73]:
x_train

array([[ 0.        , -0.70710678, -0.53440659, -0.6512485 ,  0.23732285,
        -0.70710678,  0.        ],
       [ 0.        ,  1.41421356, -0.8667311 , -0.761531  , -1.32603808,
         1.41421356,  0.        ],
       [ 0.        , -0.70710678,  1.40113768,  1.4127795 ,  1.08871524,
        -0.70710678,  0.        ]])

# model

In [76]:
from sklearn.linear_model import LogisticRegression

In [78]:
classifier = LogisticRegression(random_state=0)

In [80]:
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [82]:
LogisticRegression(random_state=0)

LogisticRegression(random_state=0)

# prediction

In [85]:
y_pred = classifier.predict(x_test)

In [87]:
y_pred

array([1, 0], dtype=int64)

In [89]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]]


# confusion matrix and accuracy

In [92]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [94]:
cn = confusion_matrix(y_test,y_pred)
cn

array([[1, 0],
       [0, 1]], dtype=int64)

In [96]:
accuracy_score(y_test,y_pred)


1.0